version: '3'
services:
  ecsdemo-nodejs:
    image: vladiko/test-node
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: test-node
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: test-node
