apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node
  labels:
    app: test-node
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-node
    spec:
      containers:
      - image: vladiko/test-node
        imagePullPolicy: Always
        name: test-node
        ports:
        - containerPort: 3000
          protocol: TCP
